# Generated by Django 3.2 on 2021-10-12 06:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
